# Sample configuration file for product-service (product-service.yml)

server:
  port: 8082 # Default port for product-service

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://product-db:5432/product_service_db
    username: ${DB_PRODUCT_USERNAME:-postgres}
    password: ${DB_PRODUCT_PASSWORD:-postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:-rabbitmq}
    port: ${RABBITMQ_PORT:-5672}
    username: ${RABBITMQ_USERNAME:-guest}
    password: ${RABBITMQ_PASSWORD:-guest}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:-http://service-registry:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Application-specific properties for Product Service
app:
  sampleProperty: "ProductServiceSpecificValue"
